name: dc-fmri

channels:
  - default
  - conda-forge

dependencies:
  - python=3.8.*
  - pip
  - osfclient
  - git
  - git-annex
  - datalad=0.14.4
  - matplotlib=3.0.3
  - nibabel=3.2.2
  - nilearn=0.7.0
  - numpy=1.15.1
  - pandas=0.24.2
  - seaborn=0.11.2

  - pip:
      - datalad-installer
      - pybids
